<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup>
		<Description>
			Provides integration for easily registering existing implementations, provided by dotRMDY.SyncSupport,
			with MvvmCross.
		</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="JetBrains.Annotations" Version="2025.2.4" PrivateAssets="All" />
		<PackageReference Include="MvvmCross" Version="10.1.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\dotRMDY.SyncSupport\dotRMDY.SyncSupport.csproj"/>
	</ItemGroup>

</Project>