<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup>
		<Description>
			Provides some implementations for services that can help with syncing data between a local database and a remote API.
			Including baseline implementations for operation-based syncing, which is desireable for offline scenarios.
		</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="dotRMDY.Components" Version="1.2.2" />
		<PackageReference Include="dotRMDY.DataStorage.Abstractions" Version="1.2.1" />
		<PackageReference Include="JetBrains.Annotations" Version="2025.2.4" PrivateAssets="All" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
		<PackageReference Include="Refit" Version="14.0.1" />
	</ItemGroup>

</Project>